home: 首页
archives: 文章归档
about: 关于作者
categories: 分类
series: 系列文章
search: 搜索
searchPlaceHolder: 请输入关键字
tags: 标签
tagcloud: 标签云
video: 视频资源
help: 关于本站
links: 友情链接
book: 悦读
music: 音乐
cloud: 资源
prev: <i class="iconfont icon-back"></i>
next: <i class="iconfont icon-right"></i>
comment: 留言
page: 第 %d 页
recent_posts: 最新文章
newer: 上一篇
older: 下一篇
share: 分享
theme_by: Theme by
rss_feed: RSS Feed
category: Category
tag: Tag
connect: '联系我们'
post_total_count: 嗯，目前共计%d篇文章
read_more: '阅读全文'
contents: 文章目录
views: 热度
visitors: 热度

none: 无
insight:
    hint: '请输入关键词...'
    posts: '文章'
    pages: '页面'
    photos: '相册'
    categories: '分类'
    tags: '标签'
    untitled: '(无标题)'


#category

技术:
    zh: 技术
    en: technology 
    img: http://b-ssl.duitang.com/uploads/item/201510/09/20151009102157_wFAQh.jpeg

生活:
    zh: 生活
    en: live
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/banner/writing.jpg

资源:
    zh: 资源
    en: resources
    img: https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330212811.png

随想:
    zh: 随想
    en: caprice
    img: https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330213918.png



#tag

悦读:
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/banner/reading.jpg


C语言:
    img: https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330212516.png

物联网:
    img: https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330212711.png

单片机:
    img: https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330212912.png

